/**
 * The command reference (SPEC.md §18 Session 17), generated from the command
 * tree itself: `docs/commands.md` is exactly what `yuzie --help` and every
 * `yuzie <command> --help` print, and a test fails when the two drift.
 */
import { PassThrough } from 'node:stream'
import type { Command } from 'commander'
import { commandTree, run } from './program.js'

const START =
  '<!-- commands:start (generated by `pnpm --filter @yuzie/cli run docs:commands`; do not edit) -->'
const END = '<!-- commands:end -->'

function hidden(command: Command): boolean {
  return (command as unknown as { _hidden?: boolean })._hidden === true
}

/** Every documented command, as its words: `[]` is `yuzie` itself. */
export function commandPaths(): string[][] {
  const quiet = new PassThrough()
  const program = commandTree({ stdout: quiet, stderr: quiet, stdin: quiet, env: {}, cwd: '/' })
  const paths: string[][] = [[]]
  const walk = (command: Command, prefix: string[]) => {
    for (const sub of command.commands) {
      if (hidden(sub)) continue
      const path = [...prefix, sub.name()]
      paths.push(path)
      walk(sub, path)
    }
  }
  walk(program, [])
  return paths
}

/** What `yuzie <path> --help` prints, run the way the binary runs it. */
export async function helpText(path: readonly string[]): Promise<string> {
  const stdout = new PassThrough()
  let text = ''
  stdout.on('data', (chunk: Buffer) => {
    text += chunk.toString()
  })
  await run([...path, '--help'], {
    stdout,
    stderr: stdout,
    stdin: new PassThrough(),
    env: { NO_COLOR: '1' },
    cwd: '/',
  })
  return text
}

/** The whole of `docs/commands.md`. */
export async function commandReference(): Promise<string> {
  const paths = commandPaths()
  const sections: string[] = []
  for (const path of paths) {
    const name = ['yuzie', ...path].join(' ')
    sections.push(`## \`${name}\`\n\n\`\`\`text\n${(await helpText(path)).trimEnd()}\n\`\`\`\n`)
  }
  const index = paths
    .filter((path) => path.length > 0)
    .map((path) => {
      const name = ['yuzie', ...path].join(' ')
      const anchor = name.replace(/\s+/g, '-')
      return `- [\`${name}\`](#${anchor})`
    })
  return `# Command reference

Every \`yuzie\` command, exactly as \`--help\` prints it. \`yz\` is the same program.
This file is generated from the command tree — run \`pnpm --filter @yuzie/cli run docs:commands\` after
changing a command; a test fails when this file and \`--help\` disagree.

${START}

${index.join('\n')}

${sections.join('\n')}
${END}
`
}
