-- The SQLite variant of §11.2, for single-team self-hosting (SPEC.md §10.1).
--
-- Same tables, same columns, in the same order -- a test asserts that, so the
-- two dialects cannot drift. Only the types and defaults differ:
--
--   uuid/timestamptz/jsonb -> text     SQLite has no native type for any of them
--   boolean                -> integer  0 and 1
--   bigint/smallint        -> integer  SQLite integers are already 64-bit
--   gen_random_uuid()      -> dropped  ids are generated by the application
--
CREATE TABLE users (
  id            text PRIMARY KEY,
  handle        text UNIQUE NOT NULL,
  email         text UNIQUE,
  display_name  text,
  avatar_url    text,
  kind          text NOT NULL DEFAULT 'human',
  github_login  text,
  created_at    text NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE workspaces (
  id          text PRIMARY KEY,
  slug        text UNIQUE NOT NULL,
  name        text NOT NULL,
  created_at  text NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE boards (
  id               text PRIMARY KEY,
  workspace_id     text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  slug             text NOT NULL,
  name             text NOT NULL,
  repo_remote      text,
  base_branch      text NOT NULL DEFAULT 'main',
  branch_template  text NOT NULL DEFAULT 'task/{id}-{slug}',
  next_card_no     integer NOT NULL DEFAULT 1,
  archived_at      text,
  created_at       text NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  UNIQUE (workspace_id, slug)
);

-- Board slugs are addressed globally in §12.1 (`/boards/:slug`), so they must be
-- unique across workspaces, not only within one.
CREATE UNIQUE INDEX boards_slug_key ON boards (slug);

CREATE TABLE memberships (
  board_id    text NOT NULL REFERENCES boards(id) ON DELETE CASCADE,
  user_id     text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role        text NOT NULL,
  created_at  text NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  PRIMARY KEY (board_id, user_id)
);

CREATE TABLE columns (
  id         text PRIMARY KEY,
  board_id   text NOT NULL REFERENCES boards(id) ON DELETE CASCADE,
  key        text NOT NULL,
  name       text NOT NULL,
  rank       text NOT NULL,
  semantics  text,
  wip_limit  integer,
  UNIQUE (board_id, key)
);

CREATE TABLE cards (
  id           text PRIMARY KEY,
  board_id     text NOT NULL REFERENCES boards(id) ON DELETE CASCADE,
  number       integer NOT NULL,
  column_id    text NOT NULL REFERENCES columns(id),
  rank         text NOT NULL,
  title        text NOT NULL,
  description  text,
  priority     integer,
  due_at       text,
  created_by   text REFERENCES users(id),
  archived_at  text,
  created_at   text NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at   text NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  version      integer NOT NULL DEFAULT 1,
  UNIQUE (board_id, number)
);
CREATE INDEX cards_board_column_rank ON cards (board_id, column_id, rank);

CREATE TABLE card_assignees (
  card_id  text NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
  user_id  text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (card_id, user_id)
);

CREATE TABLE labels (
  id        text PRIMARY KEY,
  board_id  text NOT NULL REFERENCES boards(id) ON DELETE CASCADE,
  name      text NOT NULL,
  color     text,
  UNIQUE (board_id, name)
);

CREATE TABLE card_labels (
  card_id   text NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
  label_id  text NOT NULL REFERENCES labels(id) ON DELETE CASCADE,
  PRIMARY KEY (card_id, label_id)
);

CREATE TABLE comments (
  id          text PRIMARY KEY,
  card_id     text NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
  author_id   text NOT NULL REFERENCES users(id),
  body        text NOT NULL,
  created_at  text NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  edited_at   text
);
CREATE INDEX comments_by_card ON comments (card_id, created_at);

CREATE TABLE checklist_items (
  id        text PRIMARY KEY,
  card_id   text NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
  position  integer NOT NULL,
  text      text NOT NULL,
  done_at   text,
  done_by   text REFERENCES users(id)
);
CREATE INDEX checklist_by_card ON checklist_items (card_id, position);

CREATE TABLE watchers (
  card_id  text NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
  user_id  text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (card_id, user_id)
);

CREATE TABLE git_links (
  card_id           text PRIMARY KEY REFERENCES cards(id) ON DELETE CASCADE,
  branch            text,
  base_branch       text,
  commit_count      integer NOT NULL DEFAULT 0,
  files_changed     integer NOT NULL DEFAULT 0,
  additions         integer NOT NULL DEFAULT 0,
  deletions         integer NOT NULL DEFAULT 0,
  pushed            integer NOT NULL DEFAULT 0,
  pr_url            text,
  pr_state          text,
  last_activity_at  text,
  updated_at        text NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE commits (
  sha           text NOT NULL,
  card_id       text NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
  author_id     text REFERENCES users(id),
  message       text,
  committed_at  text,
  PRIMARY KEY (card_id, sha)
);

CREATE TABLE anchors (
  id              text PRIMARY KEY,
  card_id         text NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
  path            text NOT NULL,
  line            integer,
  end_line        integer,
  commit_sha      text,
  primary_anchor  integer NOT NULL DEFAULT 0
);
CREATE INDEX anchors_by_card ON anchors (card_id);

CREATE TABLE events (
  board_id    text NOT NULL REFERENCES boards(id) ON DELETE CASCADE,
  seq         integer NOT NULL,
  id          text NOT NULL,
  type        text NOT NULL,
  actor_id    text REFERENCES users(id),
  card_id     text,
  card_no     integer,
  payload     text NOT NULL,
  created_at  text NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  PRIMARY KEY (board_id, seq)
);

CREATE TABLE api_tokens (
  id            text PRIMARY KEY,
  user_id       text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  board_id      text REFERENCES boards(id) ON DELETE CASCADE,
  name          text NOT NULL,
  token_hash    text NOT NULL,
  role          text NOT NULL,
  last_used_at  text,
  expires_at    text,
  revoked_at    text,
  created_at    text NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE UNIQUE INDEX api_tokens_hash ON api_tokens (token_hash);

-- Device-code flow (§12.1 POST /auth/device). Short-lived by construction.
CREATE TABLE device_codes (
  device_code  text PRIMARY KEY,
  user_code    text UNIQUE NOT NULL,
  user_id      text REFERENCES users(id) ON DELETE CASCADE,
  approved_at  text,
  consumed_at  text,
  expires_at   text NOT NULL,
  created_at   text NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- §12.1: "The server stores the key -> response for 24 h."
CREATE TABLE idempotency_keys (
  key           text NOT NULL,
  user_id       text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  method        text NOT NULL,
  path          text NOT NULL,
  request_hash  text NOT NULL,
  status        integer,
  response      text,
  created_at    text NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  PRIMARY KEY (key, user_id)
);
CREATE INDEX idempotency_expiry ON idempotency_keys (created_at);
